"""Shared constants for the swing trade finder."""

from zoneinfo import ZoneInfo

IST = ZoneInfo("Asia/Kolkata")

MODE_SWING = "SWING"

DIRECTION_LONG = "LONG"
DIRECTION_SHORT = "SHORT"

CONVICTION_A = "A"
CONVICTION_B = "B"
CONVICTION_C = "C"

SETUP_TREND_PULLBACK = "TREND_PULLBACK"
SETUP_BREAKOUT = "SWING_BREAKOUT"
SETUP_RS_LEADER = "RELATIVE_STRENGTH_LEADER"
SETUP_EMA_RECLAIM = "EMA_RECLAIM"
SETUP_BASE_BREAK = "BASE_BREAKOUT"
SETUP_FAIR_VALUE_REVERSION = "FAIR_VALUE_REVERSION"
SETUP_DISPLACEMENT_CONTINUATION = "DISPLACEMENT_CONTINUATION"
